- hosts: all
  gather_facts: false
  become: true

  roles:
    - role: install-docker
    - role: clean-container
    - role: create-network
    - role: launch-database
    - role: launch-app
    - role: launch-front
    - role: launch-proxy