- hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Stop and remove front container
      docker_container:
        name: front
        state: absent

    - name: Stop and remove database container
      docker_container:
        name: database
        state: absent

    - name: Stop and remove backend container
      docker_container:
        name: backend
        state: absent

    - name: Stop and remove httpd container
      docker_container:
        name: httpd
        state: absent