- hosts: all
  gather_facts: false
  become: true

  tasks:

  - name: Create network
    docker_network:
      name: tp03-network
      state: present
      roles:
        - name: create-network

  - name: Run Database
    docker_container:
      name: database
      image: louischarnay/tp01-postgres:1.0
      env:
        POSTGRES_USER: usr
        POSTGRES_PASSWORD: pwd
      networks:
        - name: tp03-network

  - name: Run App
    docker_container:
      name: backend
      image: louischarnay/tp01-api:1.0
      env:
        DATABASE_URL: jdbc:postgresql://database:5432/db
        DATABASE_USER: usr
        DATABASE_PASSWORD: pwd
      networks:
        - name: tp03-network
      ports:
        - "8080:8080"

  - name: Run HTTPD
    docker_container:
      name: httpd
      image: louischarnay/tp01-web:1.0
      networks:
        - name: tp03-network
      ports:
        - "80:80"
