---
# tasks file for roles/launch-proxy
  - name: Run HTTPD
    docker_container:
      name: "{{ HTTPD_NAME }}"
      image: "{{ HTTPD_IMAGE }}"
      state: absent
      networks:
        - name: "{{ NETWORK_NAME }}"
      ports:
        - "80:80"