---
# tasks file for roles/launch-proxy
  - name: Run HTTPD
    docker_container:
      name: httpd
      image: leondumestre/tp-devops-httpd:latest
      networks:
        - name: tp03-network
      ports:
        - "80:80"