---
# tasks file for roles/launch-database
  - name: Run Database
    docker_container:
      name: "{{ DATABASE_NAME }}"
      image: "{{ DATABASE_IMAGE }}"
      state: absent
      env:
        POSTGRES_DB: "{{ POSTGRES_DB }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      networks:
        - name: "{{ NETWORK_NAME }}"