---
# tasks file for roles/launch-database
  - name: Run Database
    docker_container:
      name: database
      image: louischarnay/tp01-postgres:1.0
      state: started
      env:
        POSTGRES_USER: usr
        POSTGRES_PASSWORD: pwd
      networks:
        - name: tp03-network
      ports:
        - "5432:5432"