---
# tasks file for roles/launch-app
  - name: Run App
    docker_container:
      name: backend
      image: louischarnay/tp01-api:1.0
      env:
        DATABASE_URL: jdbc:postgresql://database:5432/db
        DATABASE_USER: usr
        DATABASE_PASSWORD: pwd
      networks:
        - name: tp03-network
      ports:
        - "8080:8080"