---
# tasks file for roles/launch-app
  - name: Run App-1
    docker_container:
      name: "{{ BACKEND_NAME}}-1" 
      image: "{{ BACKEND_IMAGE }}"
      state: absent
      env:
        DATABASE_URL: "{{ DATABASE_URL }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ POSTGRES_DB }}"
      networks:
        - name: "{{ NETWORK_NAME }}"
  - name: Run App-2
    docker_container:
      name: "{{ BACKEND_NAME}}-2" 
      image: "{{ BACKEND_IMAGE }}"
      state: absent
      env:
        DATABASE_URL: "{{ DATABASE_URL }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ POSTGRES_DB }}"
      networks:
        - name: "{{ NETWORK_NAME }}"