---
# tasks file for roles/launch-app
  - name: Run App
    docker_container:
      name: "{{ BACKEND_NAME}}"
      image: "{{ BACKEND_IMAGE }}"
      state: started
      env:
        DATABASE_URL: "{{ DATABASE_URL }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ POSTGRES_DB }}"
      networks:
        - name: "{{ NETWORK_NAME }}"
      ports:
        - "8080:8080"