---
# tasks file for roles/launch-front
  - name: Run App
    docker_container:
      name: frontend
      image: louischarnay/tp03-frontend:1.0
      state: started
      networks:
        - name: tp03-network
      ports:
        - "8081:80"