---
# tasks file for roles/launch-front
  - name: Run App
    docker_container:
      name: frontend
      image: louischarnay/tp03-frontend:latest
      networks:
        - name: tp03-network
      ports:
        - "80:80"