---
# tasks file for roles/launch-front
  - name: Run App
    docker_container:
      name: "{{ FRONTEND_NAME }}"
      image: "{{ FRONTEND_IMAGE }}"
      state: started
      networks:
        - name: "{{ NETWORK_NAME }}"