name: deploy-ansible
on: 
  workflow_run:
    workflows: "build-and-push-docker-image"
    branches: main
    types: completed
  
jobs:
  deploy-ansible:
    runs-on: ubuntu-22.04
    # run only when code is compiling and tests are passing
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible playbook
        uses: dawidd66/action-ansible-playbook@v2
        with:
          playbook: TP03/ansible/playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            louis.charnay.takima.cloud