name: CI devops 2023
on:
  push:
    branches: 
      - main
      - develop 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3

     #finally build your app with the latest command
      - name: Build and test simple-api-student with Maven
        run: mvn clean verify ../TP01/simple-api-student-main/pom.xml
      
      - name: Build and test simple-api with Maven
        run: mvn clean verify ../TP01/simpleapi/pom.xml